# Generated by Django 6.0.7 on 2026-07-08 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('ana_id', models.AutoField(db_column='ana_id', primary_key=True, serialize=False)),
                ('run_at', models.CharField(max_length=50, unique=True)),
                ('lookback_days', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Analysis Logs',
                'db_table': 'analysis_log',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('django_id', models.AutoField(db_column='django_id', primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('exchange', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_code', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_name', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('thesis', models.TextField(default='')),
                ('evidence', models.TextField(default='')),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('related_industries', models.TextField(default='')),
                ('run_at', models.CharField(max_length=50)),
                ('analysis', models.ForeignKey(db_column='ana_id', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='app.analysislog')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'unique_together': {('analysis', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('django_id', models.AutoField(db_column='django_id', primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('momentum', models.FloatField(default=0.0)),
                ('policy_count', models.IntegerField(default=0)),
                ('positive_signals', models.IntegerField(default=0)),
                ('risk_signals', models.IntegerField(default=0)),
                ('key_drivers', models.TextField(default='')),
                ('evidence_policy_ids', models.TextField(default='')),
                ('analysis', models.ForeignKey(db_column='ana_id', on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='app.analysislog')),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'db_table': 'industries',
                'unique_together': {('analysis', 'code')},
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('django_id', models.AutoField(db_column='django_id', primary_key=True, serialize=False)),
                ('news_id', models.CharField(db_column='id', max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('url', models.URLField(max_length=1024)),
                ('published_date', models.CharField(blank=True, max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('agencies', models.TextField(default='')),
                ('run_at', models.CharField(max_length=50)),
                ('analysis', models.ForeignKey(db_column='ana_id', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app.analysislog')),
            ],
            options={
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'unique_together': {('analysis', 'news_id')},
            },
        ),
    ]
