# Generated by Django 6.0.7 on 2026-07-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidiaryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidiary_name', models.CharField(max_length=255, unique=True, verbose_name='子公司名稱 (小寫)')),
                ('parent_company_name', models.CharField(max_length=255, verbose_name='母公司名稱')),
            ],
            options={
                'verbose_name_plural': 'Subsidiary Mappings',
                'db_table': 'subsidiary_mapping',
            },
        ),
    ]
