# Generated by Django 6.0.7 on 2026-07-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subsidiarymapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroObservation',
            fields=[
                ('django_id', models.AutoField(db_column='django_id', primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('series_id', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Macro Observations',
                'db_table': 'macro_observations',
                'unique_together': {('series_id', 'date')},
            },
        ),
    ]
