# Generated by Django 6.0.7 on 2026-07-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_macroobservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macroobservation',
            name='fetched_at',
            field=models.CharField(default='', max_length=50),
        ),
    ]
